### ISSUE TITLE
No Deed Die on warrior or dwarf sheets?

### ISSUE THREAD

**Issue by ProgLord** [cyface/foundryvtt-dcc#101]
Maybe I'm blind, but is there no spot to enter the Deed Die on the Warrior or Dwarf sheets? I can add it into the to-hit calculation of the weapon on the equipment tab, but it won't add that same number to damage. It also won't list the Deed roll in the message dialogue unless you expand the to-hit roll.

**Comment by mooped** [comment]
@ProgLord It's a little well hidden at the moment.

If you open up the Config dialog for the sheet (on the title bar) and check 'Roll Attack Bonus' a Deed Roll button will appear at the top of the Equipment tab.

You reference this by adding '+@ab' at the end of the attack and damage rolls to reference the last rolled deed die.

This is optional to make it usable for custom classes, but in future I'd like to make this automatic on the Warrior and Dwarf sheets.

Hope that helps.

You can find some documentation here that might highlight some other subtle features: https://docs.google.com/document/d/1ZqQbo0g3TXuAzbHJSK6gvaLdQ-idqtEN85pxDVPzfjM/edit?usp=sharing

**Comment by ProgLord** [comment]
Thanks for the quick response. I didn't see the docs before, and there's a lot of stuff I didn't know in there.

But I'm still having trouble getting the deeds to work. 

I enabled the Roll Attack Bonus in the Config, which now shows the Deed Roll at the top of the Equipment tab. But it's defaulted to 0 and cannot be changed. Trying to edit the number just highlights it and clicking Deed Roll doesn't do anything.

**Comment by mooped** [comment]
@ProgLord Clicking Deed Roll should be all you need to do. Have you put the appropriate dice expression into the Attack Bonus field ie. +1d3 at level 1 - I've just confirmed it will fail to roll the deed die if there is a straight number in that field. I'll log an issue to sort that out. 

If that doesn't sort it please can you let me know which verson of Foundry and the DCC system you're running and any output from the Javascript debugger (hit F12 in Chrome or Firefox before clicking the button, capture any errors that come up in red in the Console tab).

**Comment by ProgLord** [comment]
That was it, I didn't have the Attack Bonus filled out on the character tab. I was too focused on the Deed Roll box on the equipment tab. 

Thanks for the help!
