### ISSUE TITLE
Using Critical/Fumble Tables: Roll Result in chat does not match Rolltable-Result

### ISSUE THREAD

**Issue by adotor** [cyface/foundryvtt-dcc#109]
When critical or fumble tables are registered to the module, the result of the roll and the text in the chat do not match.

I debugged into the rollCritical Functions and watched the following behavior:
1) The critical is rolled and the **rollData** preserved.
2) The **rollHTML** is rendered (based on the **rollData**).
3) The **critResult** is drawn via **table::draw** (and the **roll** is passed as parameter).

Inside the draw-Method the **roll** result is used to retrieve the result.
`foundry.js:34447: const r = this.roll({roll, recursive});`

When inspecting **r** the result differs from **roll**, i.e. it seems that the roll has been randomized again.

Example: Let's say we roll a crit and a 1 o a D4 as crit result. The a 1 is rendered. Now the text result is drawn and we roll a 4 for the text result. Then we present the text of a 4 a die result of 1.

Suggestion: Either we render roll and text result from the same data. Or maybe this is a broken contract of the draw function (and therefore an issue of foundry itself).

**Comment by mooped** [comment]
Rendering the roll and the result from the same data would be consistent with other cases where we roll on tables in the system.
