### ISSUE TITLE
Zero level characters should be importable from Purple Sorceror JSON or plain text character generator output

### ISSUE THREAD

**Issue by mooped** [cyface/foundryvtt-dcc#11]
Purple Sorceror supports generating characters as plain text (actually HTML) or JSON (500 characters at a time only).

The Zero level generator supports both Plain Text and JSON modes while the upper level generator supports only the plain text modes.

Parsing these will make it very easy to quickly bring pregenerated characters into FoundryVTT. Using Purple Sorceror for character generation avoids dependency on the many tables that are required to correctly generate a DCC character.

Long term it would be interesting to investigate whether adding a button to directly query Purple Sorceror for a character would be feasible (with appropriate permission and a solution to overcome any CSRF issues).

Plain text zero level example:
https://purplesorcerer.com/create.php?oc=rulebook&mode=3d6&stats=&abLow=Any&abHigh=Any&hp=normal&at=normal&display=text&sc=1

JSON zero level example:
https://purplesorcerer.com/create.php?oc=rulebook&mode=3d6&stats=&abLow=Any&abHigh=Any&hp=normal&at=normal&display=json&sc=1

Plain text upper level example (should be supported once upper level characters are added):
https://purplesorcerer.com/create.php?oc=rulebook&mode=3d6&stats=&abLow=Any&abHigh=Any&hp=normal&hpUp=normal&at=normal&lv=1&rnd=1&cl=cleric&al=lawful&ar=unarmored&w1=None&m1=0&w2=None&m2=0&display=text1u&sc=1&eu=true

**Comment by cyface** [comment]
Love it.

**Comment by cyface** [comment]
I think a good place to hook into this might be in the "Create Actor" dialog. Unsure if we can easily override that, but that would be slick. Otherwise, perhaps a new button in the Actors tab - "Create From Purple Sorcerer".  Then you could specify the options that end up being on the URL string (e.g. stat roll method), and process the results.

**Comment by mooped** [comment]
Sounds good.

Right now I've got a mostly working implementation of the JSON import, and I'll follow up with plain text import soon. To get it up and running I've overloaded the Import Stats button for PC sheets to select a parser based on whether the actor is an NPC (since the statline parser doesn't really work on PCs).

Long term fitting it into the Create Actor flow definitely sounds like the right way to go. That would also solve an issue that I've noticed where because Import Stats is populating the form on the actor sheet and the Notes field isn't a standard for input element the notes field (which I've used for the stuff Purple Sorceror outputs that doesn't yet have a home) cannot be populated in the same way.

For now I'll continue writing the parser, including generating the notes that currently get thrown away, then look at refactoring to work as you suggested.

Making token selection go smoothly (either with metadata about the GG token packs or the user's tokens) would be amazing long term.

**Comment by cyface** [comment]
Perfect.

**Comment by mooped** [comment]
Foundry doesn't seem to provide an official hook for extending teh Create Actor form.

I've submitted a pull request with the parsing code hooked up to the Import Stats button for now.

**Comment by cyface** [comment]
@mooped Do you think it's worth updating this to put all the starting equipment, etc. into the notes field?

**Comment by mooped** [comment]
@cyface Yep, there's a bit more work needed, but the parser is usable so I wanted to get it in in the current state. Will revisit to get the notes field populated soon (or individual for some of that data).

**Comment by cyface** [comment]
Sounds good, thank you for this, it works slick! I added a link to generate characters to the dialog. 👍🏻

**Comment by cyface** [comment]
This works now with cut and paste. Going to call it for now.
