### ISSUE TITLE
NPC import doesn't handle missing fields cleanly

### ISSUE THREAD

**Issue by mooped** [cyface/foundryvtt-dcc#17]
regex.replace() leaves the full statline in any fields whose regex doesn't match, which can cause problems for NPCs with an incomplete statline.

I've been working on tidying this up (see https://github.com/mooped/foundryvtt-dcc/commit/d4e57a15644998bc9844c892e3b58ca8449d33ba), but I need to improve how it handles the separators. If saves aren't present the pattern that should match the last stat won't match as it's expecting a semicolon, not a period.

The scorpion familiar in Emerald Enchanter is an extreme example of this, but it also has completely different separators.

I was hoping to accept commas, periods, and semicolons as terminators, but this if falling over in some of the unit tests (possibly special abilities containing commas, but I've not confirmed that yet).

I'm hoping to find some time to sort this out soon!

**Comment by cyface** [comment]
@mooped Thanks for looking at this!

**Comment by cyface** [comment]
This one?
`Emerald footer with claws and scorp tail (carved): Init +3; Atk claw +8 melee (1d8+1) or scorp tail +6 melee (1d6 plus magical poison (DC 14 Fort save or 1d4 Stamina loss)); AC 18; HD 8d8+8; hp 45 (25 if it fought proto demon); MV 30’; SP death throes (explodes into 2d10 10-gp gems when killed); Act 3d20 (2 claws + tail); SV Fort +6, Ref +6, Will +4; AL N.
`

**Comment by mooped** [comment]
That's the one that got me thinking about it. It's a definite edge case, but there are other statlines with missing fields that are more standard.
