### ISSUE TITLE
"Equipment" text on the Edit Equipment window is cut off at the top

### ISSUE THREAD

**Issue by ckwk** [cyface/foundryvtt-dcc#23]
If you go to the "Equipment" tab and scroll down to where you can add new equipment, create a new equipment and then select the button to edit it, in the window that pops up, "Equipment" is cut off at the top

![image](https://user-images.githubusercontent.com/44243499/90054384-08904100-dc99-11ea-91bf-f4917ca3fed1.png)

**Comment by cyface** [comment]
Confirmed this in Chrome on Mac as well
