### ISSUE TITLE
The "Spell" text in the Edit Spell window is cut off at the top

### ISSUE THREAD

**Issue by ckwk** [cyface/foundryvtt-dcc#28]
If the user goes to the "Spells" tab and attempts to edit a spell, in the window they are presented with, the "Spell" text is cut off at the top.

![image](https://user-images.githubusercontent.com/44243499/90057602-daf9c680-dc9d-11ea-9d6c-a771fb5baccd.png)

**Comment by mooped** [comment]
@ckwk Is this in the app, or in a browser?

**Comment by ckwk** [comment]
@mooped In the browser, Firefox - Linux.  Wouldn't surprise me if it was a Firefox issue

**Comment by ckwk** [comment]
As with https://github.com/cyface/foundryvtt-dcc/issues/23 , this seems to happen in the windows for editing Equipment, Mounts, and Ammunition as well.

**Comment by mooped** [comment]
Equipment, mounts, and ammunition currently share a template. Spells are a variant on that template and I consider them a rough placeholder currently.

I'll try and fix the styling on that text, but I'm also open to ideas on better ways to indicate the type of the item being viewed.
