### ISSUE TITLE
Sheet data entry - can fields be blank?

### ISSUE THREAD

**Issue by algnc** [cyface/foundryvtt-dcc#3]
On some sheets, the data fields show a grey number that is the "default" that you can just type over. In the DCC sheet I have to select everything to delete it before I enter my number, or backspace/delete key it.

**Comment by cyface** [comment]
Hey Christian!  FVTT likes to have default values for everything in the data, but I am working on a parser that lets you paste in a stat block and have it populate the NPC sheet.  I will also look at adding a "clear all" button.

**Comment by cyface** [comment]
@algnc The Clear sheet button in the header of the sheet, as well as the first pass at the NPC stat block importer is now in master if you want to give it a try!
