### ISSUE TITLE
The user can't press the "Backstab" button to roll for a backstab

### ISSUE THREAD

**Issue by ckwk** [cyface/foundryvtt-dcc#30]
All other thief abilities seem to work fine but Backstab seems to not be clickable.

![image](https://user-images.githubusercontent.com/44243499/90058625-337d9380-dc9f-11ea-803a-4e4deef9c253.png)

**Comment by mooped** [comment]
My understanding was that Backstab is not so much a skill roll as an additional attack modifier.

I might have misunderstood the rules there though.

Happy to make it rollable so it works either way. :)

**Comment by cyface** [comment]
I think the ideal case would be to have this be an alternate roll button for a given weapon that applies that bonus.  Perhaps in the meantime it could roll m1 and add the backstab bonus?
