### ISSUE TITLE
Add an input box on the spell entity for a RollTable

### ISSUE THREAD

**Issue by algnc** [cyface/foundryvtt-dcc#45]
For Spells, a box could be added to allow a GM to add a RollTable that the spell check will roll on when the d20 button is pressed next to a spell. They would have to add the table themselves.

**Comment by cyface** [comment]
I think this is a good idea; I think we should also make a system setting
to point at crit and fumble tables to do the same.

**Comment by algnc** [comment]
here is the macro I am using now which I have cobbled together. I am not sure how to make it double Level Bonus on a crit.

// Set table
let tableName = "Blessing";

// getting all actors of selected tokens
let actors = canvas.tokens.controlled.map(({ actor }) => actor);

// if there are no selected tokens, roll for the player's character.
if (actors.length < 1) {
  actors = game.users.entities.map(entity => {
    if (entity.active && entity.character !== null) {
      return entity.character;
    }
  });
}
let confirmed = false;

// Add modifier for a d20 roll
new Dialog({
    title: "Spellburn or miscellaneous bonus",
    content: `
     <form>
      <div class="form-group">
       <label>Roll Modifier:</label>
	   <input id="modifier-value" name="modifier-value" value="0"></input>
      </div>
     </form>
     `,
    buttons: {
        one: {
            icon: '<i class="fas fa-check"></i>',
            label: "Roll!",
            callback: () => confirmed = true
        },
        two: {
            icon: '<i class="fas fa-times"></i>',
            label: "Cancel",
            callback: () => confirmed = false
        }
    },
    default: "Cancel",
    close: html => {
        if (confirmed) {
		let rollModifier = parseInt(html.find('[name=modifier-value]')[0].value);
		const table = game.tables.entities.find(t => t.name === tableName);
		const roll = new Roll("1d20 + @abilities.per.mod + @details.level.value + " + rollModifier, actor.getRollData());
		const customResults = table.roll({roll});
		table.draw(customResults);
	}
}
}).render(true);
