### ISSUE TITLE
Thief skills dragged to the macro bar don't roll - throw error. Works from sheet

### ISSUE THREAD

**Issue by algnc** [cyface/foundryvtt-dcc#48]
If I drag a Thief skill to the macro bar and click the macro, they won't roll, even with the token selected. The error I get in console is:

SyntaxError: redeclaration of formal parameter actor
    callScriptMacroFunction https://bloatware.asuscomm.com:30000/modules/furnace/Macros/Macros.js:176
    renderMacro https://bloatware.asuscomm.com:30000/modules/furnace/Macros/Macros.js:197
    executeMacro https://bloatware.asuscomm.com:30000/modules/furnace/Macros/Macros.js:221
    _onClickMacro https://bloatware.asuscomm.com:30000/scripts/foundry.js:21674
    jQuery 2
        dispatch
        handle

**Comment by algnc** [comment]
Same issue with saving throws dragged to the macro bar

**Comment by mooped** [comment]
This is caused by the Furnace module. It makes an 'actor' variable available in macros that's not there when you run a macro in base Foundry.

The easy solution is for the DCC module's macros to rename their actor variable to something that doesn't clash.

**Comment by algnc** [comment]
Oh yep, disabling Furnace got it. I don't mind since I am not sure I use it.
