### ISSUE TITLE
Warrior can't roll critical hits

### ISSUE THREAD

**Issue by algnc** [cyface/foundryvtt-dcc#56]
This seems like I'm going crazy. I was testing critical hits with Warriors - both Warriors I have created can't roll crits. The default is 19-20 which seems like it makes 18 the highest roll he can roll.

If I adjust it down - to 11 - 10 becomes the highest number he can roll.

Fumble works fine, but I can't crit with the Thief or Cleric either.

To clarify, it seems like it just won't allow me to roll a 20, or whatever is in the Critical Hit range. I tried hundreds of rolls.

**Comment by mooped** [comment]
I don't think you're going mad.

Looks like the code that looks up the crit table is failing, causing the roll to fail (I'm seeing an exception in the Javascript console when this happens). It appears to be working on 0.71, but not on 0.66 which might explain why it's not been spotted.

Foundry seems to be in an awkward situation where 0.71 has a lot of nice features but the release is taking some time to get out so there are multiple versions to test with significant differences in some areas.

I'm currently working on making weapons and armor behave like other items so I'm in the area and will see if I can put in a fix soon (though we're likely going to have to remove the built in crit tables hopefully these can be replaced with a user configurable crit table).
