### ISSUE TITLE
Critical with natural 19?

### ISSUE THREAD

**Issue by johcker** [cyface/foundryvtt-dcc#60]
Rolling an attack with lvl 0 sheet and getting a natural 19 is doing a critical hit. The correct isn't only a natural 20?

**Comment by mooped** [comment]
Unfortunately this looks like the default crit range for a warrior leaking into the other characters.

As a workaround you can switch to the warrior sheet, set the crit range to 20-20 then switch back.

I'll add a mechanism to fix up existing characters automatically as part of the weapon related changes I'm currently working on.

**Comment by johcker** [comment]
Nice! The workaround worked for me.
