### ISSUE TITLE
Bad font for internationalization

### ISSUE THREAD

**Issue by johcker** [cyface/foundryvtt-dcc#61]
DDC is a very popular game in Brazil, so I started to translate the form into Brazilian Portuguese, first for my players and then contribute with your excellent work. However, the chosen font does not support special characters and accents, common in several languages other than English (such as French, Spanish and Portuguese).

An illustrative image follows.

<img width="597" alt="Captura de Tela 2020-09-07 às 21 54 42" src="https://user-images.githubusercontent.com/2867140/92422849-3b710c00-f155-11ea-9003-9fec6b79e8bd.png">

**Comment by cyface** [comment]
Hello! We are using DuVall, which is the same font that the DCC book uses. I haven’t been able to find a version of it that has the accents you need. 🤔. If you can track down a version of DuVall with accents, we can switch it out!

**Comment by johcker** [comment]
DuVall font with accents doesn't exists. So we'll not have internationalization to languages who need accents.

**Comment by mooped** [comment]
Do you know what font the translations of DCC use? It should be possible to I inject a CSS class representing the current locale so the sheets can switch based on language (or some other way of doing the same thing).

**Comment by cyface** [comment]
@johcker I used this web site: https://everythingfonts.com/accenter to try and add the accented character versions to the Duvall font.  I have replaced the fonts in the master branch with these updated font files.  See if that adds the characters you need.

**Comment by johcker** [comment]
> Do you know what font the translations of DCC use? It should be possible to inject a CSS class representing the current locale so the sheets can switch based on language (or some other way of doing the same thing).

I think that all the characters for Portuguese and Spanish are there. The last 5 rows I don't recognized, but probably it will be useful to Deutsch or another languages.

**Comment by cyface** [comment]
@johcker it sounds like my updated font file has what you need! That is good to hear. We’ll get that released in the next few days.
