### ISSUE TITLE
Fumble to char-0 always rolling 0.

### ISSUE THREAD

**Issue by johcker** [cyface/foundryvtt-dcc#62]
I tried lots of rolls. But all the fumble rollings always result in 0 in the Roll table.

**Comment by mooped** [comment]
Looks like currently we roll it, but always display result 0. I've found where this happens so I can make a fix.

**Comment by johcker** [comment]
<img width="602" alt="Captura de Tela 2020-09-09 às 00 01 45" src="https://user-images.githubusercontent.com/2867140/92614712-bf7cde00-f292-11ea-81ff-4209e666cc75.png">

My workaround was fill the field with the roll for the table fumble char lvl 0. However I don't know if the lucky modifier is already being used to roll the fumble table, so I put the modifier  manually.

One option to avoid this bug maybe put the Unequiped "equip" prefilled into the lvl 0 sheet as default.

**Comment by mooped** [comment]
Thanks for investigating further. I'm in the process of reworking weapons and armor and this is something that should be resolved as a result of those incoming changes.

Currently luck modifier is calculated automatically for crit/fumble rolls. This is a bit inconsistent with the other modifier on the sheet that roll whatever modifier is in the box.

We will need to do something special for monster crits and fumbles too. They should be modified by the attacking/defending PC's luck which is going to require them to show a prompt (or maybe an inline form in the chat to make it less disruptive).
