### ISSUE TITLE
Attribute Rolls Should be Draggable as Macros

### ISSUE THREAD

**Issue by cyface** [cyface/foundryvtt-dcc#7]
Right now you can drag an attack into the macro hotbar, but not attributes.

You should be able to drag an attribute label into the hotbar to roll Luck checks, for example.

**Comment by mooped** [comment]
I've done a bit of digging and have a plan of attack for this.

Any thoughts on reworking the current weapon macros in hot bars? Currently the label is that of the dragged weapon, but the macro created rolls the equivalent weapon slot of the selected token.

I think my preferred alternative would be for the macro to find a weapon on the selected actor with the matching name. This way the user doesn't roll an unexpected weapon if the wrong token is selected, and the stats don't go state (as they could if the weapon stats were cached in the macro).

**Comment by cyface** [comment]
@mooped I agree it's weird that it says "sword" in the hotbar, but really just rolls weapon 1.  That said, for NPCs, it's incredibly helpful to be able to click on any given NPC, and just the basic 'attack 1' button. 🤔

For long-term play, I think most people would prefer if the macro button updated to their actual attack name, but for purposes of keeping it simple, I'm honestly wondering if it might be best to just change the macro text to say "Melee #1", or something like that, so it's at least accurate. :)

I'm open to treating PCs and NPCs differently for macros as well - e.g. take a weapon name OR m1/r1 as the input to the rollWeaponAttack function, and for PCs default to weapon name, and NPCs default to 'Melee #1'.  What do you think?

Or maybe default to rolling melee 1 if the matching attack name can't be found?
