### ISSUE TITLE
Handle crits for funky dice

### ISSUE THREAD

**Issue by mooped** [cyface/foundryvtt-dcc#70]
Find a way to implement crits when rolling larger dice or for halflings rolling d16s for two weapon attacks.

**Comment by mooped** [comment]
I'm not entirely sure how to approach this. Whether a non-d20 is a crit is quite situational (Halflings basically) so the options as I see it are to hardcode something for a few cases or add lots of fiddly config options.

The chat filter that highlights the dice is now quite configurable - you can tag each dice in a roll expression with a crit and fumble threshold - but we need to drive it from somewhere.

**Comment by cyface** [comment]
I vote for just hard-coding it in the data for halflings in the base system, and we can figure out how to override in the future with add-ons.

**Comment by adotor** [comment]
What about having a critRange for each weapon that is handled the same way as the action die: it could eitehr be inherited from the character or be overridden for each weapon?

This way it schould be possible to create all the edge cases that apply to high dexterity dual wielding characters.

I implemented a showcase:
https://github.com/cyface/foundryvtt-dcc/pull/112

**Comment by mooped** [comment]
Thanks @adotor. I've merged your changes plus a couple of tweaks.
