### ISSUE TITLE
Beta .7.3 seems to remove the breakdown for dice results

### ISSUE THREAD

**Issue by algnc** [cyface/foundryvtt-dcc#78]
Under the new beta, when you click a dice result it only shows the dice roll, not the modifiers. Not sure if this is expected behavior from Foundry now, or if it can be worked around.

![image](https://user-images.githubusercontent.com/7275595/95077861-323a7700-06e2-11eb-8de1-29de01ed6af4.png)

**Comment by mooped** [comment]
Yep. This is the issue I was referring to under #66. Seems to be a change that came in with 0.7.2.

I'll close the other issue as this is a better description.

I've got a minor improvement that cleans up the formular shown when you hover (in the new version) on my wip branch, but it's not a full fix. Some investigation is needed to work out the best way to rework the attack roll output with the recent changes.

**Comment by mooped** [comment]
This seems to be the way Foundry does it now. I have however tidied up the tooltop that gives you the dice expression.

![image](https://user-images.githubusercontent.com/371357/97056854-db59ec00-1581-11eb-83fe-debe77a02e0a.png)

Do you still feel it's worth a larger rework?

**Comment by algnc** [comment]
That looks fine
