### ISSUE TITLE
Add a spells tab to NPC sheet

### ISSUE THREAD

**Issue by algnc** [cyface/foundryvtt-dcc#79]
It would be nice to have a spell tab for NPCs with a spell check stat box so they can cast spells like PCs. I tried changing an NPC to a Wizard and the NPC closed, and wouldn't open back up :)

**Comment by mooped** [comment]
I have this working on my WIP branch. NPCs have a spells tab and all PCs can optionally have a spells tab in addition to a custom skills tab.

I had to make a few tweaks to get it working which will hopefully fix the issue you had with the sheet refusing to open once set to use the wizard sheet.
