### ISSUE TITLE
allow +dice in initiative

### ISSUE THREAD

**Issue by algnc** [cyface/foundryvtt-dcc#86]
The Mutant in MCC has +dice to initiative, +1d3 for example. It would be nice if their initiative could be +1+1d3 for example.

**Comment by mooped** [comment]
![image](https://user-images.githubusercontent.com/371357/97056482-07c13880-1581-11eb-89e0-1867e09c281b.png)

How do you feel about this solution @algnc ?

It also allows handling the 1 handed/2 handed situation also while keeping the validation on the modifier section.

**Comment by mooped** [comment]
I've not applied it to NPCs or zeroes yet. NPCs usually always roll a d20 and zeroes have enough problems, though other judges may disagree.

**Comment by algnc** [comment]
That looks great
