### ISSUE TITLE
Roll attacks with the standard dice roller so Dice So Nice can be used

### ISSUE THREAD

**Issue by algnc** [cyface/foundryvtt-dcc#93]
If the standard dice roller were used for attacks, Dice So Nice would pick up dice rolls. Some players really like using Dice So Nice because it feels more like rolling dice.

**Comment by mooped** [comment]
I'm tempted to make this a system config setting.

**Comment by cyface** [comment]
I am not a fan of how much 3D dice rolls slow things down, so yeah, would prefer a setting. 👍🏻

**Comment by algnc** [comment]
sounds good
