### ISSUE TITLE
Sometimes the SPEED field empties out after input, seems connected to apostrophe for ft

### ISSUE THREAD

**Issue by algnc** [cyface/foundryvtt-dcc#97]
On some monsters, it seems like the SPEED field empties out sometimes after entering a MV with an apostrophe. It happens on import and manual input. Nothing is written to the console.

https://imgur.com/a/jQUxsHwp

**Comment by mooped** [comment]
Yep, it's the apostrophe on the speed field. The validation on the form input is expecting a number, and when it doesn't find one (the apostrophe is enough for it to not count, unfortunately) it gets thrown away.

Options are to remove the apostrophe in the importers, or add a custom handlebars helper to format speeds. I think I prefer the second as it will also fix up any user input in this field.
