### ISSUE TITLE
add an option to show what was rolled for a crit

### ISSUE THREAD

**Issue by algnc** [cyface/foundryvtt-dcc#98]
it would be nice if Critical Hits showed what the number was they rolled. it could be an option.

**Comment by mooped** [comment]
I've added a roll result similar to the attack and damage roll results, so you can see the die roll and formula. I think this can be an 'always on' feature, especially in the case where there are no tables loaded for it to use.

![image](https://user-images.githubusercontent.com/371357/98863337-1e5ffe80-2460-11eb-9034-c64813a03ff5.png)
